<a href="https://colab.research.google.com/github/PhwTha00/pythonbtvn6/blob/main/baitapmatran.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
A = np.array([[10, 1, 2],[9,7,4],[0,2,1]])
B = np.array([[2, 3, 4],[0,4,2],[3,2,1]])
print(A)
print(B)

[[10  1  2]
 [ 9  7  4]
 [ 0  2  1]]
[[2 3 4]
 [0 4 2]
 [3 2 1]]


In [4]:
# 1. Phép tính AB
result1 = np.dot(A, B)
print("AB:")
print(result1)

AB:
[[26 38 44]
 [30 63 54]
 [ 3 10  5]]


In [5]:
# 2. Phép tính BA^T * A * B^T
result2 = np.dot(np.dot(B, A.T), np.dot(A, B.T))
print("BA^T * A * B^T:")
print(result2)

BA^T * A * B^T:
[[4086 2328 3579]
 [2328 1460 1942]
 [3579 1942 3206]]


In [6]:
# 3. Phép tính AB^T * BA^T
result3 = np.dot(np.dot(A, B.T), np.dot(B, A.T))
print("AB^T * BA^T:")
print(result3)

AB^T * BA^T:
[[2181 3523  560]
 [3523 6346 1135]
 [ 560 1135  225]]


In [8]:
# Nhận xét về kết quả của biểu thức 3 và biểu thức 2
if np.array_equal(result3, result2):
    print("Kết quả của biểu thức 3 và biểu thức 2 là giống nhau.")
else:
    print("Kết quả của biểu thức 3 và biểu thức 2 là khác nhau.")



Kết quả của biểu thức 3 và biểu thức 2 là khác nhau.


In [9]:
# Tính toán các thuộc tính của ma trận A
rank_A = np.linalg.matrix_rank(A)
det_A = np.linalg.det(A)
inv_A = np.linalg.inv(A)
trace_A = np.trace(A)

print("\nThuộc tính của ma trận A:")
print("Rank của A:", rank_A)
print("Determinant của A:", det_A)
print("Ma trận nghịch đảo của A:")
print(inv_A)
print("Trace của A:", trace_A)


Thuộc tính của ma trận A:
Rank của A: 3
Determinant của A: 16.999999999999993
Ma trận nghịch đảo của A:
[[-0.05882353  0.17647059 -0.58823529]
 [-0.52941176  0.58823529 -1.29411765]
 [ 1.05882353 -1.17647059  3.58823529]]
Trace của A: 18


In [10]:
# 1. Concatenate ma trận A và ma trận B theo dòng.
concatenated_rows = np.concatenate((A, B), axis=0)
print("\nConcatenated theo dòng:")
print(concatenated_rows)


Concatenated theo dòng:
[[10  1  2]
 [ 9  7  4]
 [ 0  2  1]
 [ 2  3  4]
 [ 0  4  2]
 [ 3  2  1]]


In [11]:
# 2. Reshape ma trận A thành vecto
reshaped_vector = np.reshape(A, (-1,))
print("\nReshape thành vecto:")
print(reshaped_vector)


Reshape thành vecto:
[10  1  2  9  7  4  0  2  1]


In [12]:
# 1. Phân phối xác suất sau khi đi qua hàm softmax các dòng của A
softmax_probabilities = np.apply_along_axis(lambda x: np.exp(x) / np.sum(np.exp(x)), axis=1, arr=A)
print("\nPhân phối xác suất sau khi đi qua hàm softmax các dòng của A:")
print(softmax_probabilities)


Phân phối xác suất sau khi đi qua hàm softmax các dòng của A:
[[9.99541338e-01 1.23353201e-04 3.35308764e-04]
 [8.75600595e-01 1.18499655e-01 5.89975040e-03]
 [9.00305732e-02 6.65240956e-01 2.44728471e-01]]


In [13]:
# 2. Tìm ra nhãn dự báo cho mỗi dòng
predicted_labels = np.argmax(softmax_probabilities, axis=1)
print("\nNhãn dự báo cho mỗi dòng:")
print(predicted_labels)


Nhãn dự báo cho mỗi dòng:
[0 0 1]


In [14]:
# 3. Tính tổng, trung bình, min, max của mỗi dòng
sum_rows = np.sum(A, axis=1)
mean_rows = np.mean(A, axis=1)
min_rows = np.min(A, axis=1)
max_rows = np.max(A, axis=1)

print("\nTổng các dòng của A:", sum_rows)
print("Trung bình các dòng của A:", mean_rows)
print("Giá trị nhỏ nhất của mỗi dòng của A:", min_rows)
print("Giá trị lớn nhất của mỗi dòng của A:", max_rows)


Tổng các dòng của A: [13 20  3]
Trung bình các dòng của A: [4.33333333 6.66666667 1.        ]
Giá trị nhỏ nhất của mỗi dòng của A: [1 4 0]
Giá trị lớn nhất của mỗi dòng của A: [10  9  2]
