<a href="https://colab.research.google.com/github/PhwTha00/pythonbtvn6/blob/main/baitapmang.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Viết chương trình người dùng nhập vào 2 mảng 2 chiều có cùng kích thước (với điều kiện không có số 0) Thực hiện các phép toán cộng, trừ, nhân, chia các phần tử của 2 mảng đó.

Tính tổng các phần tử theo cột của mảng cuối cùng. (np.sum)
Tính tích các phần tử theo hàng của mảng cuối cùng. (np.prod)

In [2]:
import numpy as np
import timeit

In [19]:
rows = int(input("Nhập số hàng của mảng: "))
cols = int(input("Nhập số cột của mảng: "))


Nhập số hàng của mảng: 2
Nhập số cột của mảng: 3


In [30]:
print("Nhập các phần tử của mảng thứ nhất:")
array1 = np.zeros((rows, cols), dtype=float)
for i in range(rows):
    for j in range(cols):
        array1[i][j] = float(input(f"Nhập phần tử [{i}][{j}]: "))

# Kiểm tra mảng có chứa số 0 không
while 0 in array1:
    print("Mảng không được chứa số 0. Vui lòng nhập lại.")
    array1 = np.zeros((rows, cols), dtype=float)
    for i in range(rows):
        for j in range(cols):
            array1[i][j] = float(input(f"Nhập phần tử [{i}][{j}]: "))
np.set_printoptions(formatter={'float': lambda x: "{: .0f}".format(x)})
print("Mảng thứ nhất:")
print(array1)

Nhập các phần tử của mảng thứ nhất:
Nhập phần tử [0][0]: 1
Nhập phần tử [0][1]: 3
Nhập phần tử [0][2]: 5
Nhập phần tử [1][0]: 2
Nhập phần tử [1][1]: 7
Nhập phần tử [1][2]: 6
Mảng thứ nhất:
[[ 1  3  5]
 [ 2  7  6]]


In [31]:
print("Nhập các phần tử của mảng thứ hai:")
array2 = np.zeros((rows, cols), dtype=float)
for i in range(rows):
    for j in range(cols):
        array2[i][j] = float(input(f"Nhập phần tử [{i}][{j}]: "))

# Kiểm tra mảng có chứa số 0 không
while 0 in array2:
    print("Mảng không được chứa số 0. Vui lòng nhập lại.")
    array2 = np.zeros((rows, cols), dtype=float)
    for i in range(rows):
        for j in range(cols):
            array2[i][j] = float(input(f"Nhập phần tử [{i}][{j}]: "))
np.set_printoptions(formatter={'float': lambda x: "{: .0f}".format(x)})
print("Mảng thứ hai:")
print(array2)

Nhập các phần tử của mảng thứ hai:
Nhập phần tử [0][0]: 4
Nhập phần tử [0][1]: 3
Nhập phần tử [0][2]: 8
Nhập phần tử [1][0]: 5
Nhập phần tử [1][1]: 9
Nhập phần tử [1][2]: 2
Mảng thứ hai:
[[ 4  3  8]
 [ 5  9  2]]


In [32]:
sum_array = array1 + array2
print("Tổng của hai mảng:")
print(sum_array)

Tổng của hai mảng:
[[ 5  6  13]
 [ 7  16  8]]


In [33]:
difference_array = array1 - array2
print("Hiệu của hai mảng:")
print(difference_array)

Hiệu của hai mảng:
[[-3  0 -3]
 [-3 -2  4]]


In [34]:
product_array = array1 * array2
print("Tích của hai mảng:")
print(product_array)

Tích của hai mảng:
[[ 4  9  40]
 [ 10  63  12]]


In [35]:
quotient_array = np.divide(array1, array2, where=array2 != 0)
print("Thương của hai mảng:")
print(quotient_array)

Thương của hai mảng:
[[ 0  1  1]
 [ 0  1  3]]


In [36]:
column_sum = np.sum(quotient_array, axis=0)
print("Tổng các phần tử theo cột của mảng cuối cùng:", column_sum)

Tổng các phần tử theo cột của mảng cuối cùng: [ 1  2  4]


In [37]:
row_product = np.prod(product_array, axis=1)
print("Tích các phần tử theo hàng của mảng cuối cùng:", row_product)


Tích các phần tử theo hàng của mảng cuối cùng: [ 1440  7560]
